version: '3.8'

networks:
  app:
    driver: bridge

services:
  api:
    container_name: api
    build:
      context: ./
      cache_from:
        - my-base-image:nx-base
      dockerfile: ./apps/api/Dockerfile
    image: api:nx-dev
    ports:
      - 3333:3333
      - 3030:3030
    environment:
      PORT: 3333
    networks:
      - app
    restart: always
    env_file:
      - .env

  webapp:
    container_name: webapp
    build:
      context: .
      cache_from:
        - nginx:1.23.0-alpine
      dockerfile: ./apps/webapp/Dockerfile
    image: webapp:nx-dev
    ports:
      - 4200:80
    environment:
      PORT: 4200
    networks:
      - app
    restart: always
    env_file:
      - .env
