version: '3.8'

networks:
  app:
    driver: bridge

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    networks:
      - app
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
    environment:
      - DEFAULT_HOST=adballoon.me

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    depends_on:
      - 'nginx-proxy'
    networks:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
      - ./conf.d:/etc/nginx/conf.d
    environment:
      - DEFAULT_EMAIL=unihubone@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy # Add this line

  api:
    container_name: api
    image: ghcr.io/uoft-utsc-cs-sandbox/unihub/api:latest
    expose:
      - 3000
      - 3030
    environment:
      - VIRTUAL_HOST=api.adballoon.me
      - LETSENCRYPT_HOST=api.adballoon.me
      - LETSENCRYPT_EMAIL=unihubone@gmail.com
    networks:
      - app
    restart: always
    env_file:
      - .env

  webapp:
    container_name: webapp
    image: ghcr.io/uoft-utsc-cs-sandbox/unihub/webapp:latest
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=adballoon.me
      - LETSENCRYPT_HOST=adballoon.me
      - LETSENCRYPT_EMAIL=unihubone@gmail.com
    networks:
      - app
    restart: always
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - redisdata:/var/lib/redis
    ports:
      - 6379:6379
    networks:
      - app
    restart: always

  ion-sfu:
    container_name: ion-sfu
    image: pionwebrtc/ion-sfu:latest-jsonrpc
    ports:
      - 8000:7000
      - 5000-5200:5000-5200/udp
    networks:
      - app
    restart: always
    environment:
      - VIRTUAL_HOST=ion.adballoon.me
      - LETSENCRYPT_HOST=ion.adballoon.me
      - LETSENCRYPT_EMAIL=unihubone@gmail.com

volumes:
  redisdata:
