version: '3.8'

networks:
  app:
    driver: bridge

services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./certbot/lib:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app

  api:
    container_name: api
    image: ghcr.io/uoft-utsc-cs-sandbox/unihub/api:latest
    ports:
      - 3333:3333
      - 3030:3030
    environment:
      PORT: 3333
    networks:
      - app
    restart: always
    env_file:
      - .env

  webapp:
    container_name: webapp
    image: ghcr.io/uoft-utsc-cs-sandbox/unihub/webapp:latest
    ports:
      - 4200:80
    environment:
      PORT: 4200
    volumes:
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./certbot/lib:/var/lib/letsencrypt
    networks:
      - app
    restart: always
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - redisdata:/var/lib/redis
    ports:
      - 6379:6379
    networks:
      - app
    restart: always

  ion-sfu:
    container_name: ion-sfu
    image: pionwebrtc/ion-sfu:latest-jsonrpc
    ports:
      - 8000:7000
      - 5000-5200:5000-5200/udp
    networks:
      - app
    restart: always

volumes:
  redisdata:
