name: Run Prettier
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Prettier
        run: npm install prettier && npx prettier --check .
